# Generated by Django 4.1.1 on 2022-09-19 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('isbn_no', models.CharField(max_length=20)),
                ('publication', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=20)),
                ('rack_no', models.CharField(max_length=10)),
                ('no_of_copy', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='books-images')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='student-images/')),
                ('fine', models.FloatField(default=0)),
                ('tag', models.CharField(default='none', max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='IssueBookModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bookmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentmodel')),
            ],
            options={
                'db_table': 'issue_book',
            },
        ),
    ]
