# Generated by Django 4.0.4 on 2022-05-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentmodel_tag_alter_issuebookmodel_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebookmodel',
            name='issue_date',
            field=models.DateField(),
        ),
    ]
