# Generated by Django 4.0.4 on 2022-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_issuebookmodel_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='edition',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(upload_to='books-images'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='publication',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
